(cl:defpackage niryo_robot_msgs-msg
  (:use )
  (:export
   "<BASICOBJECT>"
   "BASICOBJECT"
   "<BASICOBJECTARRAY>"
   "BASICOBJECTARRAY"
   "<BUSSTATE>"
   "BUSSTATE"
   "<COMMANDSTATUS>"
   "COMMANDSTATUS"
   "<HARDWARESTATUS>"
   "HARDWARESTATUS"
   "<MOTORHEADER>"
   "MOTORHEADER"
   "<OBJECTPOSE>"
   "OBJECTPOSE"
   "<RPY>"
   "RPY"
   "<ROBOTSTATE>"
   "ROBOTSTATE"
   "<SOFTWAREVERSION>"
   "SOFTWAREVERSION"
  ))

