(cl:defpackage niryo_robot_programs_manager_v2-msg
  (:use )
  (:export
   "<EXECUTEPROGRAMACTION>"
   "EXECUTEPROGRAMACTION"
   "<EXECUTEPROGRAMACTIONFEEDBACK>"
   "EXECUTEPROGRAMACTIONFEEDBACK"
   "<EXECUTEPROGRAMACTIONGOAL>"
   "EXECUTEPROGRAMACTIONGOAL"
   "<EXECUTEPROGRAMACTIONRESULT>"
   "EXECUTEPROGRAMACTIONRESULT"
   "<EXECUTEPROGRAMFEEDBACK>"
   "EXECUTEPROGRAMFEEDBACK"
   "<EXECUTEPROGRAMGOAL>"
   "EXECUTEPROGRAMGOAL"
   "<EXECUTEPROGRAMRESULT>"
   "EXECUTEPROGRAMRESULT"
   "<PROGRAM>"
   "PROGRAM"
   "<PROGRAMLIST>"
   "PROGRAMLIST"
  ))

