; Auto-generated. Do not edit!


(cl:in-package niryo_robot_programs_manager_v2-msg)


;//! \htmlinclude ExecuteProgramResult.msg.html

(cl:defclass <ExecuteProgramResult> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:fixnum
    :initform 0)
   (message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass ExecuteProgramResult (<ExecuteProgramResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteProgramResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteProgramResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name niryo_robot_programs_manager_v2-msg:<ExecuteProgramResult> is deprecated: use niryo_robot_programs_manager_v2-msg:ExecuteProgramResult instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <ExecuteProgramResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_robot_programs_manager_v2-msg:status-val is deprecated.  Use niryo_robot_programs_manager_v2-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <ExecuteProgramResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_robot_programs_manager_v2-msg:message-val is deprecated.  Use niryo_robot_programs_manager_v2-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteProgramResult>) ostream)
  "Serializes a message object of type '<ExecuteProgramResult>"
  (cl:let* ((signed (cl:slot-value msg 'status)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteProgramResult>) istream)
  "Deserializes a message object of type '<ExecuteProgramResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteProgramResult>)))
  "Returns string type for a message object of type '<ExecuteProgramResult>"
  "niryo_robot_programs_manager_v2/ExecuteProgramResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteProgramResult)))
  "Returns string type for a message object of type 'ExecuteProgramResult"
  "niryo_robot_programs_manager_v2/ExecuteProgramResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteProgramResult>)))
  "Returns md5sum for a message object of type '<ExecuteProgramResult>"
  "09803e1f4a40b6f2352e453a75b02d0b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteProgramResult)))
  "Returns md5sum for a message object of type 'ExecuteProgramResult"
  "09803e1f4a40b6f2352e453a75b02d0b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteProgramResult>)))
  "Returns full string definition for message of type '<ExecuteProgramResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%int16 status~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteProgramResult)))
  "Returns full string definition for message of type 'ExecuteProgramResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%int16 status~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteProgramResult>))
  (cl:+ 0
     2
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteProgramResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteProgramResult
    (cl:cons ':status (status msg))
    (cl:cons ':message (message msg))
))
