// Generated by gencpp from file niryo_robot_arm_commander/GetIKResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETIKRESPONSE_H
#define NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETIKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_arm_commander
{
template <class ContainerAllocator>
struct GetIKResponse_
{
  typedef GetIKResponse_<ContainerAllocator> Type;

  GetIKResponse_()
    : status(0)
    , message()
    , joints()  {
    }
  GetIKResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIKResponse_

typedef ::niryo_robot_arm_commander::GetIKResponse_<std::allocator<void> > GetIKResponse;

typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetIKResponse > GetIKResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetIKResponse const> GetIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_arm_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ed6a5a3c5cec26ad2c3c58206ce47e4";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ed6a5a3c5cec26aULL;
  static const uint64_t static_value2 = 0xd2c3c58206ce47e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_arm_commander/GetIKResponse";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"float32[] joints\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_arm_commander::GetIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETIKRESPONSE_H
