# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from niryo_robot_vision/ActiveDebugTopics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ActiveDebugTopics(genpy.Message):
  _md5sum = "10965b7aa16fcc09509da71fe3d98caa"
  _type = "niryo_robot_vision/ActiveDebugTopics"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool red_channel
bool green_channel
bool blue_channel
bool any_channel
bool markers"""
  __slots__ = ['red_channel','green_channel','blue_channel','any_channel','markers']
  _slot_types = ['bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       red_channel,green_channel,blue_channel,any_channel,markers

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActiveDebugTopics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.red_channel is None:
        self.red_channel = False
      if self.green_channel is None:
        self.green_channel = False
      if self.blue_channel is None:
        self.blue_channel = False
      if self.any_channel is None:
        self.any_channel = False
      if self.markers is None:
        self.markers = False
    else:
      self.red_channel = False
      self.green_channel = False
      self.blue_channel = False
      self.any_channel = False
      self.markers = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.red_channel, _x.green_channel, _x.blue_channel, _x.any_channel, _x.markers))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.red_channel, _x.green_channel, _x.blue_channel, _x.any_channel, _x.markers,) = _get_struct_5B().unpack(str[start:end])
      self.red_channel = bool(self.red_channel)
      self.green_channel = bool(self.green_channel)
      self.blue_channel = bool(self.blue_channel)
      self.any_channel = bool(self.any_channel)
      self.markers = bool(self.markers)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.red_channel, _x.green_channel, _x.blue_channel, _x.any_channel, _x.markers))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.red_channel, _x.green_channel, _x.blue_channel, _x.any_channel, _x.markers,) = _get_struct_5B().unpack(str[start:end])
      self.red_channel = bool(self.red_channel)
      self.green_channel = bool(self.green_channel)
      self.blue_channel = bool(self.blue_channel)
      self.any_channel = bool(self.any_channel)
      self.markers = bool(self.markers)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
