(cl:defpackage ttl_driver-msg
  (:use )
  (:export
   "<ARRAYMOTORHARDWARESTATUS>"
   "ARRAYMOTORHARDWARESTATUS"
   "<CALIBRATIONSTATUS>"
   "CALIBRATIONSTATUS"
   "<MOTORCOMMAND>"
   "MOTORCOMMAND"
   "<MOTORHARDWARESTATUS>"
   "MOTORHARDWARESTATUS"
  ))

