(cl:defpackage niryo_robot_led_ring-srv
  (:use )
  (:export
   "GETLEDCOLORS"
   "<GETLEDCOLORS-REQUEST>"
   "GETLEDCOLORS-REQUEST"
   "<GETLEDCOLORS-RESPONSE>"
   "GETLEDCOLORS-RESPONSE"
   "LEDUSER"
   "<LEDUSER-REQUEST>"
   "LEDUSER-REQUEST"
   "<LEDUSER-RESPONSE>"
   "LEDUSER-RESPONSE"
   "SETLEDCOLOR"
   "<SETLEDCOLOR-REQUEST>"
   "SETLEDCOLOR-REQUEST"
   "<SETLEDCOLOR-RESPONSE>"
   "SETLEDCOLOR-RESPONSE"
  ))

