// Generated by gencpp from file niryo_robot_vision/ActiveDebugTopics.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_VISION_MESSAGE_ACTIVEDEBUGTOPICS_H
#define NIRYO_ROBOT_VISION_MESSAGE_ACTIVEDEBUGTOPICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_vision
{
template <class ContainerAllocator>
struct ActiveDebugTopics_
{
  typedef ActiveDebugTopics_<ContainerAllocator> Type;

  ActiveDebugTopics_()
    : red_channel(false)
    , green_channel(false)
    , blue_channel(false)
    , any_channel(false)
    , markers(false)  {
    }
  ActiveDebugTopics_(const ContainerAllocator& _alloc)
    : red_channel(false)
    , green_channel(false)
    , blue_channel(false)
    , any_channel(false)
    , markers(false)  {
  (void)_alloc;
    }



   typedef uint8_t _red_channel_type;
  _red_channel_type red_channel;

   typedef uint8_t _green_channel_type;
  _green_channel_type green_channel;

   typedef uint8_t _blue_channel_type;
  _blue_channel_type blue_channel;

   typedef uint8_t _any_channel_type;
  _any_channel_type any_channel;

   typedef uint8_t _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> const> ConstPtr;

}; // struct ActiveDebugTopics_

typedef ::niryo_robot_vision::ActiveDebugTopics_<std::allocator<void> > ActiveDebugTopics;

typedef boost::shared_ptr< ::niryo_robot_vision::ActiveDebugTopics > ActiveDebugTopicsPtr;
typedef boost::shared_ptr< ::niryo_robot_vision::ActiveDebugTopics const> ActiveDebugTopicsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator1> & lhs, const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator2> & rhs)
{
  return lhs.red_channel == rhs.red_channel &&
    lhs.green_channel == rhs.green_channel &&
    lhs.blue_channel == rhs.blue_channel &&
    lhs.any_channel == rhs.any_channel &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator1> & lhs, const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10965b7aa16fcc09509da71fe3d98caa";
  }

  static const char* value(const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10965b7aa16fcc09ULL;
  static const uint64_t static_value2 = 0x509da71fe3d98caaULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_vision/ActiveDebugTopics";
  }

  static const char* value(const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool red_channel\n"
"bool green_channel\n"
"bool blue_channel\n"
"bool any_channel\n"
"bool markers\n"
;
  }

  static const char* value(const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red_channel);
      stream.next(m.green_channel);
      stream.next(m.blue_channel);
      stream.next(m.any_channel);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActiveDebugTopics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator>& v)
  {
    s << indent << "red_channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red_channel);
    s << indent << "green_channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green_channel);
    s << indent << "blue_channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue_channel);
    s << indent << "any_channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.any_channel);
    s << indent << "markers: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.markers);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_VISION_MESSAGE_ACTIVEDEBUGTOPICS_H
