// Generated by gencpp from file niryo_robot_vision/ActivateDebugTopicsRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_VISION_MESSAGE_ACTIVATEDEBUGTOPICSREQUEST_H
#define NIRYO_ROBOT_VISION_MESSAGE_ACTIVATEDEBUGTOPICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_vision/ActiveDebugTopics.h>

namespace niryo_robot_vision
{
template <class ContainerAllocator>
struct ActivateDebugTopicsRequest_
{
  typedef ActivateDebugTopicsRequest_<ContainerAllocator> Type;

  ActivateDebugTopicsRequest_()
    : topics()  {
    }
  ActivateDebugTopicsRequest_(const ContainerAllocator& _alloc)
    : topics(_alloc)  {
  (void)_alloc;
    }



   typedef  ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator>  _topics_type;
  _topics_type topics;





  typedef boost::shared_ptr< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActivateDebugTopicsRequest_

typedef ::niryo_robot_vision::ActivateDebugTopicsRequest_<std::allocator<void> > ActivateDebugTopicsRequest;

typedef boost::shared_ptr< ::niryo_robot_vision::ActivateDebugTopicsRequest > ActivateDebugTopicsRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_vision::ActivateDebugTopicsRequest const> ActivateDebugTopicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.topics == rhs.topics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a180b8b00d4a3a59b916fbf2afaefa98";
  }

  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa180b8b00d4a3a59ULL;
  static const uint64_t static_value2 = 0xb916fbf2afaefa98ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_vision/ActivateDebugTopicsRequest";
  }

  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_vision/ActiveDebugTopics topics\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_vision/ActiveDebugTopics\n"
"bool red_channel\n"
"bool green_channel\n"
"bool blue_channel\n"
"bool any_channel\n"
"bool markers\n"
;
  }

  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivateDebugTopicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_vision::ActivateDebugTopicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "topics: ";
    s << std::endl;
    Printer< ::niryo_robot_vision::ActiveDebugTopics_<ContainerAllocator> >::stream(s, indent + "  ", v.topics);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_VISION_MESSAGE_ACTIVATEDEBUGTOPICSREQUEST_H
