// Generated by gencpp from file niryo_robot_vision/ActivateDebugTopics.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_VISION_MESSAGE_ACTIVATEDEBUGTOPICS_H
#define NIRYO_ROBOT_VISION_MESSAGE_ACTIVATEDEBUGTOPICS_H

#include <ros/service_traits.h>


#include <niryo_robot_vision/ActivateDebugTopicsRequest.h>
#include <niryo_robot_vision/ActivateDebugTopicsResponse.h>


namespace niryo_robot_vision
{

struct ActivateDebugTopics
{

typedef ActivateDebugTopicsRequest Request;
typedef ActivateDebugTopicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActivateDebugTopics
} // namespace niryo_robot_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_vision::ActivateDebugTopics > {
  static const char* value()
  {
    return "c0c5123a51741d038cae1b93404df52b";
  }

  static const char* value(const ::niryo_robot_vision::ActivateDebugTopics&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_vision::ActivateDebugTopics > {
  static const char* value()
  {
    return "niryo_robot_vision/ActivateDebugTopics";
  }

  static const char* value(const ::niryo_robot_vision::ActivateDebugTopics&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_vision::ActivateDebugTopicsRequest> should match
// service_traits::MD5Sum< ::niryo_robot_vision::ActivateDebugTopics >
template<>
struct MD5Sum< ::niryo_robot_vision::ActivateDebugTopicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_vision::ActivateDebugTopics >::value();
  }
  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_vision::ActivateDebugTopicsRequest> should match
// service_traits::DataType< ::niryo_robot_vision::ActivateDebugTopics >
template<>
struct DataType< ::niryo_robot_vision::ActivateDebugTopicsRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_vision::ActivateDebugTopics >::value();
  }
  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_vision::ActivateDebugTopicsResponse> should match
// service_traits::MD5Sum< ::niryo_robot_vision::ActivateDebugTopics >
template<>
struct MD5Sum< ::niryo_robot_vision::ActivateDebugTopicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_vision::ActivateDebugTopics >::value();
  }
  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_vision::ActivateDebugTopicsResponse> should match
// service_traits::DataType< ::niryo_robot_vision::ActivateDebugTopics >
template<>
struct DataType< ::niryo_robot_vision::ActivateDebugTopicsResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_vision::ActivateDebugTopics >::value();
  }
  static const char* value(const ::niryo_robot_vision::ActivateDebugTopicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_VISION_MESSAGE_ACTIVATEDEBUGTOPICS_H
