// Generated by gencpp from file niryo_robot_led_ring/GetLedColorsResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_LED_RING_MESSAGE_GETLEDCOLORSRESPONSE_H
#define NIRYO_ROBOT_LED_RING_MESSAGE_GETLEDCOLORSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace niryo_robot_led_ring
{
template <class ContainerAllocator>
struct GetLedColorsResponse_
{
  typedef GetLedColorsResponse_<ContainerAllocator> Type;

  GetLedColorsResponse_()
    : led_ring_colors()
    , status(0)
    , message()  {
    }
  GetLedColorsResponse_(const ContainerAllocator& _alloc)
    : led_ring_colors(_alloc)
    , status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::ColorRGBA_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::ColorRGBA_<ContainerAllocator> >::other >  _led_ring_colors_type;
  _led_ring_colors_type led_ring_colors;

   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetLedColorsResponse_

typedef ::niryo_robot_led_ring::GetLedColorsResponse_<std::allocator<void> > GetLedColorsResponse;

typedef boost::shared_ptr< ::niryo_robot_led_ring::GetLedColorsResponse > GetLedColorsResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_led_ring::GetLedColorsResponse const> GetLedColorsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.led_ring_colors == rhs.led_ring_colors &&
    lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_led_ring

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a00eb631a727c358bd52d7c6213b37a5";
  }

  static const char* value(const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa00eb631a727c358ULL;
  static const uint64_t static_value2 = 0xbd52d7c6213b37a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_led_ring/GetLedColorsResponse";
  }

  static const char* value(const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/ColorRGBA[] led_ring_colors\n"
"int32 status\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_ring_colors);
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLedColorsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_led_ring::GetLedColorsResponse_<ContainerAllocator>& v)
  {
    s << indent << "led_ring_colors[]" << std::endl;
    for (size_t i = 0; i < v.led_ring_colors.size(); ++i)
    {
      s << indent << "  led_ring_colors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "    ", v.led_ring_colors[i]);
    }
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_LED_RING_MESSAGE_GETLEDCOLORSRESPONSE_H
