// Generated by gencpp from file niryo_robot_led_ring/GetLedColors.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_LED_RING_MESSAGE_GETLEDCOLORS_H
#define NIRYO_ROBOT_LED_RING_MESSAGE_GETLEDCOLORS_H

#include <ros/service_traits.h>


#include <niryo_robot_led_ring/GetLedColorsRequest.h>
#include <niryo_robot_led_ring/GetLedColorsResponse.h>


namespace niryo_robot_led_ring
{

struct GetLedColors
{

typedef GetLedColorsRequest Request;
typedef GetLedColorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLedColors
} // namespace niryo_robot_led_ring


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_led_ring::GetLedColors > {
  static const char* value()
  {
    return "a00eb631a727c358bd52d7c6213b37a5";
  }

  static const char* value(const ::niryo_robot_led_ring::GetLedColors&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_led_ring::GetLedColors > {
  static const char* value()
  {
    return "niryo_robot_led_ring/GetLedColors";
  }

  static const char* value(const ::niryo_robot_led_ring::GetLedColors&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_led_ring::GetLedColorsRequest> should match
// service_traits::MD5Sum< ::niryo_robot_led_ring::GetLedColors >
template<>
struct MD5Sum< ::niryo_robot_led_ring::GetLedColorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_led_ring::GetLedColors >::value();
  }
  static const char* value(const ::niryo_robot_led_ring::GetLedColorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_led_ring::GetLedColorsRequest> should match
// service_traits::DataType< ::niryo_robot_led_ring::GetLedColors >
template<>
struct DataType< ::niryo_robot_led_ring::GetLedColorsRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_led_ring::GetLedColors >::value();
  }
  static const char* value(const ::niryo_robot_led_ring::GetLedColorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_led_ring::GetLedColorsResponse> should match
// service_traits::MD5Sum< ::niryo_robot_led_ring::GetLedColors >
template<>
struct MD5Sum< ::niryo_robot_led_ring::GetLedColorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_led_ring::GetLedColors >::value();
  }
  static const char* value(const ::niryo_robot_led_ring::GetLedColorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_led_ring::GetLedColorsResponse> should match
// service_traits::DataType< ::niryo_robot_led_ring::GetLedColors >
template<>
struct DataType< ::niryo_robot_led_ring::GetLedColorsResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_led_ring::GetLedColors >::value();
  }
  static const char* value(const ::niryo_robot_led_ring::GetLedColorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_LED_RING_MESSAGE_GETLEDCOLORS_H
