// Generated by gencpp from file niryo_robot_msgs/BasicObjectArray.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_BASICOBJECTARRAY_H
#define NIRYO_ROBOT_MSGS_MESSAGE_BASICOBJECTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_msgs/BasicObject.h>

namespace niryo_robot_msgs
{
template <class ContainerAllocator>
struct BasicObjectArray_
{
  typedef BasicObjectArray_<ContainerAllocator> Type;

  BasicObjectArray_()
    : objects()  {
    }
  BasicObjectArray_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct BasicObjectArray_

typedef ::niryo_robot_msgs::BasicObjectArray_<std::allocator<void> > BasicObjectArray;

typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObjectArray > BasicObjectArrayPtr;
typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObjectArray const> BasicObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfe0a8412a62b82237847c2cddde7923";
  }

  static const char* value(const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfe0a8412a62b822ULL;
  static const uint64_t static_value2 = 0x37847c2cddde7923ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/BasicObjectArray";
  }

  static const char* value(const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/BasicObject[] objects\n"
"================================================================================\n"
"MSG: niryo_robot_msgs/BasicObject\n"
"string name\n"
"string description\n"
;
  }

  static const char* value(const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BasicObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_msgs::BasicObjectArray_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_BASICOBJECTARRAY_H
