// Generated by gencpp from file niryo_robot_msgs/BasicObject.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_BASICOBJECT_H
#define NIRYO_ROBOT_MSGS_MESSAGE_BASICOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_msgs
{
template <class ContainerAllocator>
struct BasicObject_
{
  typedef BasicObject_<ContainerAllocator> Type;

  BasicObject_()
    : name()
    , description()  {
    }
  BasicObject_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> const> ConstPtr;

}; // struct BasicObject_

typedef ::niryo_robot_msgs::BasicObject_<std::allocator<void> > BasicObject;

typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObject > BasicObjectPtr;
typedef boost::shared_ptr< ::niryo_robot_msgs::BasicObject const> BasicObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_msgs::BasicObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_msgs::BasicObject_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::BasicObject_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_msgs::BasicObject_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::BasicObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a319d5d0d68cf65447a451755dbc01b";
  }

  static const char* value(const ::niryo_robot_msgs::BasicObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a319d5d0d68cf65ULL;
  static const uint64_t static_value2 = 0x447a451755dbc01bULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/BasicObject";
  }

  static const char* value(const ::niryo_robot_msgs::BasicObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string description\n"
;
  }

  static const char* value(const ::niryo_robot_msgs::BasicObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BasicObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_msgs::BasicObject_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_BASICOBJECT_H
