// Generated by gencpp from file niryo_robot_msgs/GetFloatListResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_GETFLOATLISTRESPONSE_H
#define NIRYO_ROBOT_MSGS_MESSAGE_GETFLOATLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_msgs
{
template <class ContainerAllocator>
struct GetFloatListResponse_
{
  typedef GetFloatListResponse_<ContainerAllocator> Type;

  GetFloatListResponse_()
    : values()
    , status(0)
    , message()  {
    }
  GetFloatListResponse_(const ContainerAllocator& _alloc)
    : values(_alloc)
    , status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _values_type;
  _values_type values;

   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFloatListResponse_

typedef ::niryo_robot_msgs::GetFloatListResponse_<std::allocator<void> > GetFloatListResponse;

typedef boost::shared_ptr< ::niryo_robot_msgs::GetFloatListResponse > GetFloatListResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_msgs::GetFloatListResponse const> GetFloatListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values &&
    lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4451316e97dfda37b6fe1ea8066c7c25";
  }

  static const char* value(const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4451316e97dfda37ULL;
  static const uint64_t static_value2 = 0xb6fe1ea8066c7c25ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/GetFloatListResponse";
  }

  static const char* value(const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] values\n"
"int32 status\n"
"string message\n"
;
  }

  static const char* value(const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFloatListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_msgs::GetFloatListResponse_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_GETFLOATLISTRESPONSE_H
