// Generated by gencpp from file niryo_robot_msgs/GetFloatList.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_GETFLOATLIST_H
#define NIRYO_ROBOT_MSGS_MESSAGE_GETFLOATLIST_H

#include <ros/service_traits.h>


#include <niryo_robot_msgs/GetFloatListRequest.h>
#include <niryo_robot_msgs/GetFloatListResponse.h>


namespace niryo_robot_msgs
{

struct GetFloatList
{

typedef GetFloatListRequest Request;
typedef GetFloatListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFloatList
} // namespace niryo_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_msgs::GetFloatList > {
  static const char* value()
  {
    return "4451316e97dfda37b6fe1ea8066c7c25";
  }

  static const char* value(const ::niryo_robot_msgs::GetFloatList&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_msgs::GetFloatList > {
  static const char* value()
  {
    return "niryo_robot_msgs/GetFloatList";
  }

  static const char* value(const ::niryo_robot_msgs::GetFloatList&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_msgs::GetFloatListRequest> should match
// service_traits::MD5Sum< ::niryo_robot_msgs::GetFloatList >
template<>
struct MD5Sum< ::niryo_robot_msgs::GetFloatListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_msgs::GetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::GetFloatListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_msgs::GetFloatListRequest> should match
// service_traits::DataType< ::niryo_robot_msgs::GetFloatList >
template<>
struct DataType< ::niryo_robot_msgs::GetFloatListRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_msgs::GetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::GetFloatListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_msgs::GetFloatListResponse> should match
// service_traits::MD5Sum< ::niryo_robot_msgs::GetFloatList >
template<>
struct MD5Sum< ::niryo_robot_msgs::GetFloatListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_msgs::GetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::GetFloatListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_msgs::GetFloatListResponse> should match
// service_traits::DataType< ::niryo_robot_msgs::GetFloatList >
template<>
struct DataType< ::niryo_robot_msgs::GetFloatListResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_msgs::GetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::GetFloatListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_GETFLOATLIST_H
