// Generated by gencpp from file niryo_robot_msgs/GetNameDescriptionListResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_GETNAMEDESCRIPTIONLISTRESPONSE_H
#define NIRYO_ROBOT_MSGS_MESSAGE_GETNAMEDESCRIPTIONLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_msgs/BasicObject.h>

namespace niryo_robot_msgs
{
template <class ContainerAllocator>
struct GetNameDescriptionListResponse_
{
  typedef GetNameDescriptionListResponse_<ContainerAllocator> Type;

  GetNameDescriptionListResponse_()
    : status(0)
    , message()
    , name_list()
    , description_list()
    , objects()  {
    }
  GetNameDescriptionListResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , name_list(_alloc)
    , description_list(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_list_type;
  _name_list_type name_list;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _description_list_type;
  _description_list_type description_list;

   typedef std::vector< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNameDescriptionListResponse_

typedef ::niryo_robot_msgs::GetNameDescriptionListResponse_<std::allocator<void> > GetNameDescriptionListResponse;

typedef boost::shared_ptr< ::niryo_robot_msgs::GetNameDescriptionListResponse > GetNameDescriptionListResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_msgs::GetNameDescriptionListResponse const> GetNameDescriptionListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.name_list == rhs.name_list &&
    lhs.description_list == rhs.description_list &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eff00794274414fcb8d225743b92508";
  }

  static const char* value(const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eff00794274414fULL;
  static const uint64_t static_value2 = 0xcb8d225743b92508ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/GetNameDescriptionListResponse";
  }

  static const char* value(const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"# this service embed both old and new way to structure the datas in order to stay compatible with NS1/2\n"
"string[] name_list\n"
"string[] description_list\n"
"BasicObject[] objects\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_msgs/BasicObject\n"
"string name\n"
"string description\n"
;
  }

  static const char* value(const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.name_list);
      stream.next(m.description_list);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNameDescriptionListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_msgs::GetNameDescriptionListResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "name_list[]" << std::endl;
    for (size_t i = 0; i < v.name_list.size(); ++i)
    {
      s << indent << "  name_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name_list[i]);
    }
    s << indent << "description_list[]" << std::endl;
    for (size_t i = 0; i < v.description_list.size(); ++i)
    {
      s << indent << "  description_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description_list[i]);
    }
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_msgs::BasicObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_GETNAMEDESCRIPTIONLISTRESPONSE_H
