// Generated by gencpp from file niryo_robot_msgs/SetFloatListRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_SETFLOATLISTREQUEST_H
#define NIRYO_ROBOT_MSGS_MESSAGE_SETFLOATLISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_msgs
{
template <class ContainerAllocator>
struct SetFloatListRequest_
{
  typedef SetFloatListRequest_<ContainerAllocator> Type;

  SetFloatListRequest_()
    : values()  {
    }
  SetFloatListRequest_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloatListRequest_

typedef ::niryo_robot_msgs::SetFloatListRequest_<std::allocator<void> > SetFloatListRequest;

typedef boost::shared_ptr< ::niryo_robot_msgs::SetFloatListRequest > SetFloatListRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_msgs::SetFloatListRequest const> SetFloatListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c9c4a808bfa8ef83980bb0222137bf";
  }

  static const char* value(const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c9c4a808bfa8efULL;
  static const uint64_t static_value2 = 0x83980bb0222137bfULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/SetFloatListRequest";
  }

  static const char* value(const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] values\n"
;
  }

  static const char* value(const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloatListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_msgs::SetFloatListRequest_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_SETFLOATLISTREQUEST_H
