// Generated by gencpp from file niryo_robot_msgs/SetFloatList.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_SETFLOATLIST_H
#define NIRYO_ROBOT_MSGS_MESSAGE_SETFLOATLIST_H

#include <ros/service_traits.h>


#include <niryo_robot_msgs/SetFloatListRequest.h>
#include <niryo_robot_msgs/SetFloatListResponse.h>


namespace niryo_robot_msgs
{

struct SetFloatList
{

typedef SetFloatListRequest Request;
typedef SetFloatListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloatList
} // namespace niryo_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_msgs::SetFloatList > {
  static const char* value()
  {
    return "aad4aec377eeec0ea90e866c6d677783";
  }

  static const char* value(const ::niryo_robot_msgs::SetFloatList&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_msgs::SetFloatList > {
  static const char* value()
  {
    return "niryo_robot_msgs/SetFloatList";
  }

  static const char* value(const ::niryo_robot_msgs::SetFloatList&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_msgs::SetFloatListRequest> should match
// service_traits::MD5Sum< ::niryo_robot_msgs::SetFloatList >
template<>
struct MD5Sum< ::niryo_robot_msgs::SetFloatListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_msgs::SetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::SetFloatListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_msgs::SetFloatListRequest> should match
// service_traits::DataType< ::niryo_robot_msgs::SetFloatList >
template<>
struct DataType< ::niryo_robot_msgs::SetFloatListRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_msgs::SetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::SetFloatListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_msgs::SetFloatListResponse> should match
// service_traits::MD5Sum< ::niryo_robot_msgs::SetFloatList >
template<>
struct MD5Sum< ::niryo_robot_msgs::SetFloatListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_msgs::SetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::SetFloatListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_msgs::SetFloatListResponse> should match
// service_traits::DataType< ::niryo_robot_msgs::SetFloatList >
template<>
struct DataType< ::niryo_robot_msgs::SetFloatListResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_msgs::SetFloatList >::value();
  }
  static const char* value(const ::niryo_robot_msgs::SetFloatListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_SETFLOATLIST_H
