// Generated by gencpp from file niryo_robot_metrics/GetMetric.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_METRICS_MESSAGE_GETMETRIC_H
#define NIRYO_ROBOT_METRICS_MESSAGE_GETMETRIC_H

#include <ros/service_traits.h>


#include <niryo_robot_metrics/GetMetricRequest.h>
#include <niryo_robot_metrics/GetMetricResponse.h>


namespace niryo_robot_metrics
{

struct GetMetric
{

typedef GetMetricRequest Request;
typedef GetMetricResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMetric
} // namespace niryo_robot_metrics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_metrics::GetMetric > {
  static const char* value()
  {
    return "3c7e8f79bf57a60d05456cd506c553a8";
  }

  static const char* value(const ::niryo_robot_metrics::GetMetric&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_metrics::GetMetric > {
  static const char* value()
  {
    return "niryo_robot_metrics/GetMetric";
  }

  static const char* value(const ::niryo_robot_metrics::GetMetric&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_metrics::GetMetricRequest> should match
// service_traits::MD5Sum< ::niryo_robot_metrics::GetMetric >
template<>
struct MD5Sum< ::niryo_robot_metrics::GetMetricRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_metrics::GetMetric >::value();
  }
  static const char* value(const ::niryo_robot_metrics::GetMetricRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_metrics::GetMetricRequest> should match
// service_traits::DataType< ::niryo_robot_metrics::GetMetric >
template<>
struct DataType< ::niryo_robot_metrics::GetMetricRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_metrics::GetMetric >::value();
  }
  static const char* value(const ::niryo_robot_metrics::GetMetricRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_metrics::GetMetricResponse> should match
// service_traits::MD5Sum< ::niryo_robot_metrics::GetMetric >
template<>
struct MD5Sum< ::niryo_robot_metrics::GetMetricResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_metrics::GetMetric >::value();
  }
  static const char* value(const ::niryo_robot_metrics::GetMetricResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_metrics::GetMetricResponse> should match
// service_traits::DataType< ::niryo_robot_metrics::GetMetric >
template<>
struct DataType< ::niryo_robot_metrics::GetMetricResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_metrics::GetMetric >::value();
  }
  static const char* value(const ::niryo_robot_metrics::GetMetricResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_METRICS_MESSAGE_GETMETRIC_H
