// Generated by gencpp from file niryo_robot_metrics/Metric.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_METRICS_MESSAGE_METRIC_H
#define NIRYO_ROBOT_METRICS_MESSAGE_METRIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_metrics
{
template <class ContainerAllocator>
struct Metric_
{
  typedef Metric_<ContainerAllocator> Type;

  Metric_()
    : name()
    , value()
    , unit()  {
    }
  Metric_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(_alloc)
    , unit(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _unit_type;
  _unit_type unit;





  typedef boost::shared_ptr< ::niryo_robot_metrics::Metric_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_metrics::Metric_<ContainerAllocator> const> ConstPtr;

}; // struct Metric_

typedef ::niryo_robot_metrics::Metric_<std::allocator<void> > Metric;

typedef boost::shared_ptr< ::niryo_robot_metrics::Metric > MetricPtr;
typedef boost::shared_ptr< ::niryo_robot_metrics::Metric const> MetricConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_metrics::Metric_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_metrics::Metric_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_metrics::Metric_<ContainerAllocator1> & lhs, const ::niryo_robot_metrics::Metric_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value &&
    lhs.unit == rhs.unit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_metrics::Metric_<ContainerAllocator1> & lhs, const ::niryo_robot_metrics::Metric_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_metrics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_metrics::Metric_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_metrics::Metric_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_metrics::Metric_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
{
  static const char* value()
  {
    return "898aa783673b4282b5ca67c01b7159da";
  }

  static const char* value(const ::niryo_robot_metrics::Metric_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x898aa783673b4282ULL;
  static const uint64_t static_value2 = 0xb5ca67c01b7159daULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_metrics/Metric";
  }

  static const char* value(const ::niryo_robot_metrics::Metric_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string value\n"
"string unit\n"
;
  }

  static const char* value(const ::niryo_robot_metrics::Metric_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
      stream.next(m.unit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Metric_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_metrics::Metric_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_metrics::Metric_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
    s << indent << "unit: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.unit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_METRICS_MESSAGE_METRIC_H
