(cl:defpackage joints_interface-srv
  (:use )
  (:export
   "FACTORYCALIBRATION"
   "<FACTORYCALIBRATION-REQUEST>"
   "FACTORYCALIBRATION-REQUEST"
   "<FACTORYCALIBRATION-RESPONSE>"
   "FACTORYCALIBRATION-RESPONSE"
  ))

