// Auto-generated. Do not edit!

// (in-package niryo_robot_programs_manager_v2.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ExecuteProgramGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.program_id = null;
      this.code_string = null;
    }
    else {
      if (initObj.hasOwnProperty('program_id')) {
        this.program_id = initObj.program_id
      }
      else {
        this.program_id = '';
      }
      if (initObj.hasOwnProperty('code_string')) {
        this.code_string = initObj.code_string
      }
      else {
        this.code_string = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExecuteProgramGoal
    // Serialize message field [program_id]
    bufferOffset = _serializer.string(obj.program_id, buffer, bufferOffset);
    // Serialize message field [code_string]
    bufferOffset = _serializer.string(obj.code_string, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExecuteProgramGoal
    let len;
    let data = new ExecuteProgramGoal(null);
    // Deserialize message field [program_id]
    data.program_id = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [code_string]
    data.code_string = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.program_id);
    length += _getByteLength(object.code_string);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'niryo_robot_programs_manager_v2/ExecuteProgramGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5773bae13e0fd7ad4bf284aea0a36603';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    string program_id
    string code_string
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExecuteProgramGoal(null);
    if (msg.program_id !== undefined) {
      resolved.program_id = msg.program_id;
    }
    else {
      resolved.program_id = ''
    }

    if (msg.code_string !== undefined) {
      resolved.code_string = msg.code_string;
    }
    else {
      resolved.code_string = ''
    }

    return resolved;
    }
};

module.exports = ExecuteProgramGoal;
