// Generated by gencpp from file conveyor_interface/GetHardwareIdRequest.msg
// DO NOT EDIT!


#ifndef CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREIDREQUEST_H
#define CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conveyor_interface
{
template <class ContainerAllocator>
struct GetHardwareIdRequest_
{
  typedef GetHardwareIdRequest_<ContainerAllocator> Type;

  GetHardwareIdRequest_()
    : id(0)  {
    }
  GetHardwareIdRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetHardwareIdRequest_

typedef ::conveyor_interface::GetHardwareIdRequest_<std::allocator<void> > GetHardwareIdRequest;

typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdRequest > GetHardwareIdRequestPtr;
typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdRequest const> GetHardwareIdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator1> & lhs, const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator1> & lhs, const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conveyor_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "541b98e964705918fa8eb206b65347b3";
  }

  static const char* value(const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x541b98e964705918ULL;
  static const uint64_t static_value2 = 0xfa8eb206b65347b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conveyor_interface/GetHardwareIdRequest";
  }

  static const char* value(const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
;
  }

  static const char* value(const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHardwareIdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conveyor_interface::GetHardwareIdRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREIDREQUEST_H
