// Generated by gencpp from file conveyor_interface/GetHardwareId.msg
// DO NOT EDIT!


#ifndef CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREID_H
#define CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREID_H

#include <ros/service_traits.h>


#include <conveyor_interface/GetHardwareIdRequest.h>
#include <conveyor_interface/GetHardwareIdResponse.h>


namespace conveyor_interface
{

struct GetHardwareId
{

typedef GetHardwareIdRequest Request;
typedef GetHardwareIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHardwareId
} // namespace conveyor_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conveyor_interface::GetHardwareId > {
  static const char* value()
  {
    return "6f74e67adad9d39e5f460edd6826c1f4";
  }

  static const char* value(const ::conveyor_interface::GetHardwareId&) { return value(); }
};

template<>
struct DataType< ::conveyor_interface::GetHardwareId > {
  static const char* value()
  {
    return "conveyor_interface/GetHardwareId";
  }

  static const char* value(const ::conveyor_interface::GetHardwareId&) { return value(); }
};


// service_traits::MD5Sum< ::conveyor_interface::GetHardwareIdRequest> should match
// service_traits::MD5Sum< ::conveyor_interface::GetHardwareId >
template<>
struct MD5Sum< ::conveyor_interface::GetHardwareIdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conveyor_interface::GetHardwareId >::value();
  }
  static const char* value(const ::conveyor_interface::GetHardwareIdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conveyor_interface::GetHardwareIdRequest> should match
// service_traits::DataType< ::conveyor_interface::GetHardwareId >
template<>
struct DataType< ::conveyor_interface::GetHardwareIdRequest>
{
  static const char* value()
  {
    return DataType< ::conveyor_interface::GetHardwareId >::value();
  }
  static const char* value(const ::conveyor_interface::GetHardwareIdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conveyor_interface::GetHardwareIdResponse> should match
// service_traits::MD5Sum< ::conveyor_interface::GetHardwareId >
template<>
struct MD5Sum< ::conveyor_interface::GetHardwareIdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conveyor_interface::GetHardwareId >::value();
  }
  static const char* value(const ::conveyor_interface::GetHardwareIdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conveyor_interface::GetHardwareIdResponse> should match
// service_traits::DataType< ::conveyor_interface::GetHardwareId >
template<>
struct DataType< ::conveyor_interface::GetHardwareIdResponse>
{
  static const char* value()
  {
    return DataType< ::conveyor_interface::GetHardwareId >::value();
  }
  static const char* value(const ::conveyor_interface::GetHardwareIdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREID_H
