// Generated by gencpp from file conveyor_interface/GetHardwareIdResponse.msg
// DO NOT EDIT!


#ifndef CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREIDRESPONSE_H
#define CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conveyor_interface
{
template <class ContainerAllocator>
struct GetHardwareIdResponse_
{
  typedef GetHardwareIdResponse_<ContainerAllocator> Type;

  GetHardwareIdResponse_()
    : status(0)
    , message()
    , hardware_id()  {
    }
  GetHardwareIdResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , hardware_id(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hardware_id_type;
  _hardware_id_type hardware_id;





  typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHardwareIdResponse_

typedef ::conveyor_interface::GetHardwareIdResponse_<std::allocator<void> > GetHardwareIdResponse;

typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdResponse > GetHardwareIdResponsePtr;
typedef boost::shared_ptr< ::conveyor_interface::GetHardwareIdResponse const> GetHardwareIdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator1> & lhs, const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.hardware_id == rhs.hardware_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator1> & lhs, const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conveyor_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73f65606aaa1d6d502da4435ed03ec8d";
  }

  static const char* value(const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73f65606aaa1d6d5ULL;
  static const uint64_t static_value2 = 0x02da4435ed03ec8dULL;
};

template<class ContainerAllocator>
struct DataType< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conveyor_interface/GetHardwareIdResponse";
  }

  static const char* value(const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 status\n"
"string message\n"
"string hardware_id\n"
"\n"
;
  }

  static const char* value(const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.hardware_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHardwareIdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conveyor_interface::GetHardwareIdResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "hardware_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hardware_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEYOR_INTERFACE_MESSAGE_GETHARDWAREIDRESPONSE_H
