// Generated by gencpp from file niryo_robot_programs_manager_v2/CreateProgramResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_CREATEPROGRAMRESPONSE_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_CREATEPROGRAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct CreateProgramResponse_
{
  typedef CreateProgramResponse_<ContainerAllocator> Type;

  CreateProgramResponse_()
    : status(0)
    , message()
    , program_id()  {
    }
  CreateProgramResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , program_id(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_id_type;
  _program_id_type program_id;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CreateProgramResponse_

typedef ::niryo_robot_programs_manager_v2::CreateProgramResponse_<std::allocator<void> > CreateProgramResponse;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::CreateProgramResponse > CreateProgramResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::CreateProgramResponse const> CreateProgramResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.program_id == rhs.program_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ca6d8672cff7c6659a48c1f65dfce0b";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ca6d8672cff7c66ULL;
  static const uint64_t static_value2 = 0x59a48c1f65dfce0bULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/CreateProgramResponse";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 status\n"
"string message\n"
"string program_id\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.program_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreateProgramResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::CreateProgramResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "program_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_CREATEPROGRAMRESPONSE_H
