// Generated by gencpp from file niryo_robot_programs_manager_v2/CreateProgram.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_CREATEPROGRAM_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_CREATEPROGRAM_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/CreateProgramRequest.h>
#include <niryo_robot_programs_manager_v2/CreateProgramResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct CreateProgram
{

typedef CreateProgramRequest Request;
typedef CreateProgramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreateProgram
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgram > {
  static const char* value()
  {
    return "55311faab2d3b7c64170cea5a33a21aa";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgram&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::CreateProgram > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/CreateProgram";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgram&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgramRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::CreateProgramRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::CreateProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::CreateProgramRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::CreateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgramResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::CreateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::CreateProgramResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::CreateProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::CreateProgramResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::CreateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::CreateProgramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_CREATEPROGRAM_H
