// Generated by gencpp from file niryo_robot_programs_manager_v2/DeleteProgramRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_DELETEPROGRAMREQUEST_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_DELETEPROGRAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct DeleteProgramRequest_
{
  typedef DeleteProgramRequest_<ContainerAllocator> Type;

  DeleteProgramRequest_()
    : program_id()  {
    }
  DeleteProgramRequest_(const ContainerAllocator& _alloc)
    : program_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_id_type;
  _program_id_type program_id;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteProgramRequest_

typedef ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<std::allocator<void> > DeleteProgramRequest;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::DeleteProgramRequest > DeleteProgramRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::DeleteProgramRequest const> DeleteProgramRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator2> & rhs)
{
  return lhs.program_id == rhs.program_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c74b4df6f78c8a2f4b510da9469347e4";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc74b4df6f78c8a2fULL;
  static const uint64_t static_value2 = 0x4b510da9469347e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/DeleteProgramRequest";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string program_id\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.program_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteProgramRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::DeleteProgramRequest_<ContainerAllocator>& v)
  {
    s << indent << "program_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_DELETEPROGRAMREQUEST_H
