// Generated by gencpp from file niryo_robot_programs_manager_v2/DeleteProgram.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_DELETEPROGRAM_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_DELETEPROGRAM_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/DeleteProgramRequest.h>
#include <niryo_robot_programs_manager_v2/DeleteProgramResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct DeleteProgram
{

typedef DeleteProgramRequest Request;
typedef DeleteProgramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteProgram
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgram > {
  static const char* value()
  {
    return "501c46b3f9338389dd9ce4d07338320f";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgram&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::DeleteProgram > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/DeleteProgram";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgram&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgramRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::DeleteProgramRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::DeleteProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::DeleteProgramRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::DeleteProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgramResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::DeleteProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::DeleteProgramResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::DeleteProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::DeleteProgramResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::DeleteProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::DeleteProgramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_DELETEPROGRAM_H
