// Generated by gencpp from file niryo_robot_programs_manager_v2/ExecuteProgramGoal.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_EXECUTEPROGRAMGOAL_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_EXECUTEPROGRAMGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct ExecuteProgramGoal_
{
  typedef ExecuteProgramGoal_<ContainerAllocator> Type;

  ExecuteProgramGoal_()
    : program_id()
    , code_string()  {
    }
  ExecuteProgramGoal_(const ContainerAllocator& _alloc)
    : program_id(_alloc)
    , code_string(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_id_type;
  _program_id_type program_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _code_string_type;
  _code_string_type code_string;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteProgramGoal_

typedef ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<std::allocator<void> > ExecuteProgramGoal;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal > ExecuteProgramGoalPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal const> ExecuteProgramGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator2> & rhs)
{
  return lhs.program_id == rhs.program_id &&
    lhs.code_string == rhs.code_string;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5773bae13e0fd7ad4bf284aea0a36603";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5773bae13e0fd7adULL;
  static const uint64_t static_value2 = 0x4bf284aea0a36603ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/ExecuteProgramGoal";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"string program_id\n"
"string code_string\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.program_id);
      stream.next(m.code_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteProgramGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::ExecuteProgramGoal_<ContainerAllocator>& v)
  {
    s << indent << "program_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program_id);
    s << indent << "code_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.code_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_EXECUTEPROGRAMGOAL_H
