// Generated by gencpp from file niryo_robot_programs_manager_v2/ExecuteProgramFeedback.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_EXECUTEPROGRAMFEEDBACK_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_EXECUTEPROGRAMFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct ExecuteProgramFeedback_
{
  typedef ExecuteProgramFeedback_<ContainerAllocator> Type;

  ExecuteProgramFeedback_()
    : output()  {
    }
  ExecuteProgramFeedback_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteProgramFeedback_

typedef ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<std::allocator<void> > ExecuteProgramFeedback;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback > ExecuteProgramFeedbackPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback const> ExecuteProgramFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/ExecuteProgramFeedback";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"string output\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteProgramFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::ExecuteProgramFeedback_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_EXECUTEPROGRAMFEEDBACK_H
