// Generated by gencpp from file niryo_robot_programs_manager_v2/GetProgramListResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMLISTRESPONSE_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_programs_manager_v2/Program.h>

namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct GetProgramListResponse_
{
  typedef GetProgramListResponse_<ContainerAllocator> Type;

  GetProgramListResponse_()
    : status(0)
    , message()
    , programs()  {
    }
  GetProgramListResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , programs(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >::other >  _programs_type;
  _programs_type programs;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetProgramListResponse_

typedef ::niryo_robot_programs_manager_v2::GetProgramListResponse_<std::allocator<void> > GetProgramListResponse;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramListResponse > GetProgramListResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramListResponse const> GetProgramListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.programs == rhs.programs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71139d068539b14853901004189dc3a";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71139d068539b14ULL;
  static const uint64_t static_value2 = 0x853901004189dc3aULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/GetProgramListResponse";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"niryo_robot_programs_manager_v2/Program[] programs\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_programs_manager_v2/Program\n"
"string program_id\n"
"string name\n"
"string description\n"
"bool has_blockly\n"
"string saved_at\n"
"string python_code\n"
"string blockly_code\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.programs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetProgramListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::GetProgramListResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "programs[]" << std::endl;
    for (size_t i = 0; i < v.programs.size(); ++i)
    {
      s << indent << "  programs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >::stream(s, indent + "    ", v.programs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMLISTRESPONSE_H
