// Generated by gencpp from file niryo_robot_programs_manager_v2/GetProgramList.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMLIST_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMLIST_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/GetProgramListRequest.h>
#include <niryo_robot_programs_manager_v2/GetProgramListResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct GetProgramList
{

typedef GetProgramListRequest Request;
typedef GetProgramListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetProgramList
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramList > {
  static const char* value()
  {
    return "b71139d068539b14853901004189dc3a";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramList&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramList > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/GetProgramList";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramList&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramListRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramList >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramList >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramListRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramList >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramListRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::GetProgramList >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramListResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramList >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramList >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramListResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramList >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramListResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::GetProgramList >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMLIST_H
