// Generated by gencpp from file niryo_robot_programs_manager_v2/GetProgramAutorunInfosResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMAUTORUNINFOSRESPONSE_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMAUTORUNINFOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct GetProgramAutorunInfosResponse_
{
  typedef GetProgramAutorunInfosResponse_<ContainerAllocator> Type;

  GetProgramAutorunInfosResponse_()
    : status(0)
    , message()
    , program_id()
    , mode(0)  {
    }
  GetProgramAutorunInfosResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , program_id(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_id_type;
  _program_id_type program_id;

   typedef int8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DISABLE)
  #undef DISABLE
#endif
#if defined(_WIN32) && defined(ONE_SHOT)
  #undef ONE_SHOT
#endif
#if defined(_WIN32) && defined(LOOP)
  #undef LOOP
#endif

  enum {
    DISABLE = 0,
    ONE_SHOT = 1,
    LOOP = 2,
  };


  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetProgramAutorunInfosResponse_

typedef ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<std::allocator<void> > GetProgramAutorunInfosResponse;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse > GetProgramAutorunInfosResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse const> GetProgramAutorunInfosResponseConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.program_id == rhs.program_id &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8981d6a455c23b2e3b12e77054c6e8d";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8981d6a455c23b2ULL;
  static const uint64_t static_value2 = 0xe3b12e77054c6e8dULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/GetProgramAutorunInfosResponse";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"\n"
"string program_id\n"
"\n"
"# Mode\n"
"int8 DISABLE = 0\n"
"int8 ONE_SHOT = 1\n"
"int8 LOOP = 2\n"
"\n"
"int8 mode\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.program_id);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetProgramAutorunInfosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "program_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program_id);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMAUTORUNINFOSRESPONSE_H
