// Generated by gencpp from file niryo_robot_programs_manager_v2/GetProgramAutorunInfos.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMAUTORUNINFOS_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMAUTORUNINFOS_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/GetProgramAutorunInfosRequest.h>
#include <niryo_robot_programs_manager_v2/GetProgramAutorunInfosResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct GetProgramAutorunInfos
{

typedef GetProgramAutorunInfosRequest Request;
typedef GetProgramAutorunInfosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetProgramAutorunInfos
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos > {
  static const char* value()
  {
    return "e8981d6a455c23b2e3b12e77054c6e8d";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/GetProgramAutorunInfos";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::GetProgramAutorunInfos >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramAutorunInfosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAMAUTORUNINFOS_H
