// Generated by gencpp from file niryo_robot_programs_manager_v2/GetProgram.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAM_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAM_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/GetProgramRequest.h>
#include <niryo_robot_programs_manager_v2/GetProgramResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct GetProgram
{

typedef GetProgramRequest Request;
typedef GetProgramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetProgram
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgram > {
  static const char* value()
  {
    return "0ade8b5e1fdf93f0f73c30b7ca75dcce";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgram&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgram > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/GetProgram";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgram&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::GetProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::GetProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::GetProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::GetProgramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::GetProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgramResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::GetProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::GetProgramResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::GetProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::GetProgramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_GETPROGRAM_H
