// Generated by gencpp from file niryo_robot_programs_manager_v2/Program.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_PROGRAM_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_PROGRAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct Program_
{
  typedef Program_<ContainerAllocator> Type;

  Program_()
    : program_id()
    , name()
    , description()
    , has_blockly(false)
    , saved_at()
    , python_code()
    , blockly_code()  {
    }
  Program_(const ContainerAllocator& _alloc)
    : program_id(_alloc)
    , name(_alloc)
    , description(_alloc)
    , has_blockly(false)
    , saved_at(_alloc)
    , python_code(_alloc)
    , blockly_code(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_id_type;
  _program_id_type program_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef uint8_t _has_blockly_type;
  _has_blockly_type has_blockly;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _saved_at_type;
  _saved_at_type saved_at;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _python_code_type;
  _python_code_type python_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _blockly_code_type;
  _blockly_code_type blockly_code;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> const> ConstPtr;

}; // struct Program_

typedef ::niryo_robot_programs_manager_v2::Program_<std::allocator<void> > Program;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::Program > ProgramPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::Program const> ProgramConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator2> & rhs)
{
  return lhs.program_id == rhs.program_id &&
    lhs.name == rhs.name &&
    lhs.description == rhs.description &&
    lhs.has_blockly == rhs.has_blockly &&
    lhs.saved_at == rhs.saved_at &&
    lhs.python_code == rhs.python_code &&
    lhs.blockly_code == rhs.blockly_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02cd6606b088c8d3c241a7b018a0926f";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02cd6606b088c8d3ULL;
  static const uint64_t static_value2 = 0xc241a7b018a0926fULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/Program";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string program_id\n"
"string name\n"
"string description\n"
"bool has_blockly\n"
"string saved_at\n"
"string python_code\n"
"string blockly_code\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.program_id);
      stream.next(m.name);
      stream.next(m.description);
      stream.next(m.has_blockly);
      stream.next(m.saved_at);
      stream.next(m.python_code);
      stream.next(m.blockly_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Program_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator>& v)
  {
    s << indent << "program_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program_id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "has_blockly: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_blockly);
    s << indent << "saved_at: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.saved_at);
    s << indent << "python_code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.python_code);
    s << indent << "blockly_code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.blockly_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_PROGRAM_H
