// Generated by gencpp from file niryo_robot_programs_manager_v2/ProgramList.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_PROGRAMLIST_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_PROGRAMLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_programs_manager_v2/Program.h>

namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct ProgramList_
{
  typedef ProgramList_<ContainerAllocator> Type;

  ProgramList_()
    : programs()  {
    }
  ProgramList_(const ContainerAllocator& _alloc)
    : programs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >::other >  _programs_type;
  _programs_type programs;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> const> ConstPtr;

}; // struct ProgramList_

typedef ::niryo_robot_programs_manager_v2::ProgramList_<std::allocator<void> > ProgramList;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ProgramList > ProgramListPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::ProgramList const> ProgramListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator2> & rhs)
{
  return lhs.programs == rhs.programs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5a3eee4c3101d45b45d481eeb8521cf";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5a3eee4c3101d45ULL;
  static const uint64_t static_value2 = 0xb45d481eeb8521cfULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/ProgramList";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/Program[] programs\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_programs_manager_v2/Program\n"
"string program_id\n"
"string name\n"
"string description\n"
"bool has_blockly\n"
"string saved_at\n"
"string python_code\n"
"string blockly_code\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.programs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProgramList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::ProgramList_<ContainerAllocator>& v)
  {
    s << indent << "programs[]" << std::endl;
    for (size_t i = 0; i < v.programs.size(); ++i)
    {
      s << indent << "  programs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_programs_manager_v2::Program_<ContainerAllocator> >::stream(s, indent + "    ", v.programs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_PROGRAMLIST_H
