// Generated by gencpp from file niryo_robot_programs_manager_v2/SetProgramAutorun.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_SETPROGRAMAUTORUN_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_SETPROGRAMAUTORUN_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/SetProgramAutorunRequest.h>
#include <niryo_robot_programs_manager_v2/SetProgramAutorunResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct SetProgramAutorun
{

typedef SetProgramAutorunRequest Request;
typedef SetProgramAutorunResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetProgramAutorun
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorun > {
  static const char* value()
  {
    return "bf5e2880d3da99b3a480c54d6ac54425";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorun&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorun > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/SetProgramAutorun";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorun&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorun >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorun >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorunResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorun >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorunResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorunResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorun >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorunResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_SETPROGRAMAUTORUN_H
