// Generated by gencpp from file niryo_robot_programs_manager_v2/SetProgramAutorunRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_SETPROGRAMAUTORUNREQUEST_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_SETPROGRAMAUTORUNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager_v2
{
template <class ContainerAllocator>
struct SetProgramAutorunRequest_
{
  typedef SetProgramAutorunRequest_<ContainerAllocator> Type;

  SetProgramAutorunRequest_()
    : program_id()
    , mode(0)  {
    }
  SetProgramAutorunRequest_(const ContainerAllocator& _alloc)
    : program_id(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _program_id_type;
  _program_id_type program_id;

   typedef int8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DISABLE)
  #undef DISABLE
#endif
#if defined(_WIN32) && defined(ONE_SHOT)
  #undef ONE_SHOT
#endif
#if defined(_WIN32) && defined(LOOP)
  #undef LOOP
#endif

  enum {
    DISABLE = 0,
    ONE_SHOT = 1,
    LOOP = 2,
  };


  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetProgramAutorunRequest_

typedef ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<std::allocator<void> > SetProgramAutorunRequest;

typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest > SetProgramAutorunRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest const> SetProgramAutorunRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator2> & rhs)
{
  return lhs.program_id == rhs.program_id &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager_v2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c59b81ad49067049c82904b639588f12";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc59b81ad49067049ULL;
  static const uint64_t static_value2 = 0xc82904b639588f12ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/SetProgramAutorunRequest";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Program id\n"
"string program_id\n"
"\n"
"# Mode\n"
"int8 DISABLE = 0\n"
"int8 ONE_SHOT = 1\n"
"int8 LOOP = 2\n"
"\n"
"int8 mode\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.program_id);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetProgramAutorunRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager_v2::SetProgramAutorunRequest_<ContainerAllocator>& v)
  {
    s << indent << "program_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.program_id);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_SETPROGRAMAUTORUNREQUEST_H
