// Generated by gencpp from file niryo_robot_programs_manager_v2/UpdateProgram.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_UPDATEPROGRAM_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_UPDATEPROGRAM_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager_v2/UpdateProgramRequest.h>
#include <niryo_robot_programs_manager_v2/UpdateProgramResponse.h>


namespace niryo_robot_programs_manager_v2
{

struct UpdateProgram
{

typedef UpdateProgramRequest Request;
typedef UpdateProgramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateProgram
} // namespace niryo_robot_programs_manager_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgram > {
  static const char* value()
  {
    return "eb0c9f7450449983be4acb7cf3218c8e";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::UpdateProgram&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager_v2::UpdateProgram > {
  static const char* value()
  {
    return "niryo_robot_programs_manager_v2/UpdateProgram";
  }

  static const char* value(const ::niryo_robot_programs_manager_v2::UpdateProgram&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgramRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::UpdateProgramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::UpdateProgramRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::UpdateProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::UpdateProgramRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::UpdateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::UpdateProgramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgramResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgram >
template<>
struct MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager_v2::UpdateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::UpdateProgramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager_v2::UpdateProgramResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager_v2::UpdateProgram >
template<>
struct DataType< ::niryo_robot_programs_manager_v2::UpdateProgramResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager_v2::UpdateProgram >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager_v2::UpdateProgramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_V2_MESSAGE_UPDATEPROGRAM_H
